services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: localdrop
      POSTGRES_PASSWORD: localdrop
      POSTGRES_DB: localdrop
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6385:6379"

  api:
    build: ./apps/api
    
    env_file:
    - ./apps/api/.env.docker

    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
